name: acosqe-env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.1
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - nltk=3.8.1
  - tqdm=4.66.2
  - jupyterlab=4.1.5
  - ipykernel=6.29.4
  - pip:
      - transformers==4.36.2
      - datasets==2.18.0
      - accelerate==0.26.1
      - sentencepiece==0.1.99
      - seqeval==1.2.2
      - evaluate==0.4.0
      - plotly==5.20.0
      # if using a custom attention visualisation module
      # - torch-attention==0.0.1 
      - torch==2.2.1
